### PR TITLE
merge this change

### PR DESCRIPTION
**Pull request by PRIYESH740**
merge the new login1

### CODE REVIEW

**Comment by shivamsingh163248** [comment]
this is new changes in profile

**Comment by PRIYESH740** [comment]
ok merge the change

**Review by shivamsingh163248 — APPROVED** [review]
this is changes

**Review by shivamsingh163248 — APPROVED** [review]

**Review by shivamsingh163248 — APPROVED** [review]
changed

**Comment by PRIYESH740** [comment]
this change is required

**Review by shivamsingh163248 — COMMENTED** [review]
changes

**Pull request merged**
